version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 10s
      interval: 1s
      retries: 10

  backend:
    depends_on:
      db:
        condition: service_healthy
    image: danilovkzn/foodgram_backend:ver.1.0.8
    restart: always
    volumes:
      - static_value:/app/back_static/
      - media_value:/app/back_media/
    env_file:
      - ./.env

  frontend:
    depends_on:
      - backend
    image: danilovkzn/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/back_static/
      - media_value:/var/html/back_media/
    restart: always  
    depends_on:
      - frontend

volumes: 
  static_value:
  media_value:
  postgres_data:

