# Generated by Django 2.2.16 on 2022-06-29 08:38

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favorites',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='uning_fields'),
        ),
        migrations.AddConstraint(
            model_name='favorites',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('recipe')), name='prevent_follows'),
        ),
    ]
