# Generated by Django 2.2.16 on 2022-06-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название ингредиента'),
        ),
    ]
