# Generated by Django 2.2.16 on 2022-06-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_author'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredientsamount',
            constraint=models.UniqueConstraint(fields=('ingredients', 'amount'), name='unique_ingredient_amount'),
        ),
    ]
