# Generated by Django 2.2.16 on 2022-06-29 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20220629_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='created',
        ),
    ]
