# Generated by Django 2.2.16 on 2022-07-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_shoppingcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ManyToManyField(related_name='in_favorite', to='recipe.Recipe', verbose_name='Рецепты'),
        ),
    ]
