# Generated by Django 2.2.16 on 2022-06-30 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_remove_recipe_created'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredients',
            unique_together=set(),
        ),
    ]
